name: Tag

# Manually create semantic version tags
on:
  workflow_dispatch: # Manual trigger only

permissions:
  contents: write # Required to create tags
  pull-requests: write # Required to comment on associated PRs
  issues: write # Required to comment on associated issues

jobs:
  tag:
    uses: ./.github/workflows/tag-core.yml
